- name: Demo on variables
  hosts: all
  vars_files: demo-vars.yaml
  vars_prompt: 
    - name: PURL  
      prompt: Enter the purl 
      private: true
  vars:
    URL: https:google.com
  tasks:
    - name: Printing the global variable
      ansible.builtin.debug:
        msg : "{{URL}}"
    
    - name: Printing the global variable
      ansible.builtin.debug:
        msg : "{{URL}}"
      vars:
        URL: https:local.com  # scope of local varaible is in this task only

    - name: Printing the global variable
      ansible.builtin.debug:
        msg : "{{CMD_URL}}" # Using command line variables
    
    - name: Printing the variables from a file 
      ansible.builtin.debug:
        msg: "{{GAME_LIVES}}"

    - name: Printing prompt url  
      ansible.builtin.debug:
        msg: "{{PURL}}"








# Variable Precendence : 
# CLI Variables  > Local Variables > Global Variables > File Variables > Prompt Variables 

    

      
